include gruvbox-material-dark-soft.conf

font_family JetBrainsMono Nerd Font
font_size 10.0

# cursor #ea6962

cursor #e5b567
cursor_text_color #1a1b26


cursor_shape block
cursor_shape_unfocused hollow

cursor_trail 25
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

cursor_blink_interval 1.25 ease-in-out
cursor_stop_blinking_after 0.0

window_padding_width 2

