[tools]
bat = "latest"
btop = "latest"
chezmoi = "latest"
doggo = "latest"
duf = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
tealdeer = "latest"
tmux = "latest"
yazi = "latest"
zoxide = "latest"
