# ─────────────────────────────────────────────
# General
# ─────────────────────────────────────────────

# Start windows/panes at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows when one is closed
set -g renumber-windows on

# Enable mouse support
set -g mouse on

# Larger scrollback history
set -g history-limit 50000

# Faster escape sequences (good for Vim/Neovim)
set -sg escape-time 10


# ─────────────────────────────────────────────
# Additional binds
# ─────────────────────────────────────────────

# Control + r to reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

# Alt+arrow to navigate windows
bind -n M-Left  previous-window
bind -n M-Right next-window

# Alt+Shift+arrow to relocate current window
bind -n M-S-Left  swap-window -t -1 \; select-window -t -1
bind -n M-S-Right swap-window -t +1 \; select-window -t +1


# ─────────────────────────────────────────────
# New window/pane behavior
# ─────────────────────────────────────────────

# Keep the current working directory when creating
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

setw -g pane-border-status off


#─────────────────────────────────────────────
#Status Bar layout, format and style
#─────────────────────────────────────────────

#True Color Enabled
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Status bar location and style
set -g status-position top
set -g status-interval 5
set -g status-style bg=black,bold,fg=brightblack

# Left status format and style
set -g status-left-length 30
set -g status-left \
"#[fg=brightblack,bold] #S #[fg=brightblack,bold]│ "

# Right status format and style
set -g status-right-length 120
set -g status-right \
"#[fg=orange,bold]#{pane_current_path} #[fg=brightblack,bold]│ #[fg=brightblack,bold]%a %Y-%m-%d %H:%M "

# Inactive windows format and style
set -g window-status-style "fg=brightblack"
set -g window-status-format "#I:#W"

# Active windows format and style
set -g window-status-current-style fg=orange,bold
set -g window-status-current-format "#I:#W"

# Tmux prompts / messages format and style
set -g message-style fg=black,bold,bg=green,bold
set -g message-command-style fg=black,bold,bg=green,bold

# # Let Kitty provide the colors rather than hard-coding
# set -g status-style "default"
# set -g pane-border-style "default"
# set -g pane-active-border-style "default"
# set -g message-style "default"
# set -g window-status-style "default"
# set -g window-status-current-style "default"

